### ISSUE TITLE
Loops not working properly

### ISSUE THREAD

**Issue by rdebath** [rafael-santiago/foobar#1]
They don't even seem to be the normal 'do-while' badness.

Usually, I'd say use the "Hello World" below, but it's vaguely possible that you meant to do the unusual cell type that you also have, in which case it'll only print "Hello".

```
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by rafael-santiago** [comment]
Something is wrong... I will take a look at this issue, thanks for the feedback.

**Comment by rafael-santiago** [comment]
Hi @rdebath

I have just applied a [bugfix](https://github.com/rafael-santiago/foobar/commit/cbab516f39af74204041cfafd8456cebaf3640be) for your issue. Now the loops present in your code seems to be working properly.

Thanks again!

**Comment by rdebath** [comment]
Yup, working fine now, even though it's weirdly sluggish with big programs like [LostKng.b](https://github.com/rdebath/LostKingdom)
